### ISSUE TITLE
[POST /projects/{projectId}/species]

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#105]
Add new species [POST /projects/{projectId}/species]
https://cameratraptw.docs.apiary.io/#/reference/projects/species

**Comment by kelp404** [comment]
改用批次修改物種 API。
https://cameratraptw.docs.apiary.io/#/reference/projects/species/update-species/200?mc=reference%2Fprojects%2Fspecies%2Fupdate-species%2F200

**Comment by cjk-halodule** [comment]
這部分文件補上後再 close 囉。要確保已經 close 的是文件也 ready 給前端作業的。

**Comment by kelp404** [comment]
文件我已經拿掉了。
