### ISSUE TITLE
[PUT /projects/{projectId}/species/{speciesId}]

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#106]
Update a species [PUT /projects/{projectId}/species/{speciesId}]
https://cameratraptw.docs.apiary.io/#/reference/projects/species/add-new-species/200?mc=reference%2Fprojects%2Fspecies%2Fadd-new-species%2F200

**Comment by kelp404** [comment]
改用批次修改物種 API。
https://cameratraptw.docs.apiary.io/#/reference/projects/species/update-species/200?mc=reference%2Fprojects%2Fspecies%2Fupdate-species%2F200

**Comment by cjk-halodule** [comment]
文件修正後關閉。@所以這支 API 要在文件上刪除嗎？

**Comment by kelp404** [comment]
文件我已經拿掉了。
