### ISSUE TITLE
[GET] /projects/{projectId}/study-areas

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#109]
Study areas [/projects/{projectId}/study-areas]
https://cameratraptw.docs.apiary.io/#/reference/projects/study-areas/list-study-areas/200?mc=reference%2Fprojects%2Fstudy-areas%2Flist-study-areas%2F200

**Comment by kelp404** [comment]
回傳的樣區資料需要新增欄位供前端實作錯誤提示。
判斷樣區關聯的 `AnnotationModel.failures`。

<img width="1145" alt="螢幕快照 2019-04-24 下午2 40 46" src="https://user-images.githubusercontent.com/1680868/56637999-98267080-669f-11e9-83f5-146cb697c41c.png">

**Comment by kelp404** [comment]
樣區需包含第一筆相機位置供繪製地圖。
https://github.com/TaiBIF/camera-trap-vueapp/issues/85
<img width="875" alt="螢幕快照 2019-04-26 下午10 32 58" src="https://user-images.githubusercontent.com/1680868/56815181-420a2680-6873-11e9-8272-9c78181b179c.png">
<img width="366" alt="螢幕快照 2019-04-26 下午10 32 43" src="https://user-images.githubusercontent.com/1680868/56815186-446c8080-6873-11e9-84de-a301fd039ad1.png">

**Comment by cjk-halodule** [comment]
Verified.

**Comment by cjk-halodule** [comment]
Related to: https://github.com/TaiBIF/camera-trap-api/issues/109
