### ISSUE TITLE
[POST] /projects/{projectId}/study-areas

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#110]
Add a study area [POST /projects/{projectId}/study-areas]
https://cameratraptw.docs.apiary.io/#/reference/projects/study-areas/add-a-study-area/200?mc=reference%2Fprojects%2Fstudy-areas%2Fadd-a-study-area%2F200

**Comment by kelp404** [comment]
回傳的樣區資料需要新增欄位供前端實作錯誤提示。
判斷樣區的 `AnnotationModel.failures`。

<img width="1145" alt="螢幕快照 2019-04-24 下午2 40 46" src="https://user-images.githubusercontent.com/1680868/56637745-f69f1f00-669e-11e9-9d6b-7bc31f23e2a1.png">
