### ISSUE TITLE
[GET] /projects/{projectId}/study-areas/{studyAreaId}/camera-locations

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#114]
Retrieve camera locations in a study area [GET /projects/{projectId}/study-areas/{studyAreaId}/camera-locations{?index,size,sort,name}]

https://cameratraptw.docs.apiary.io/#/reference/projects/camera-locations-in-study-areas

**Comment by kelp404** [comment]
補欄位供前端判斷能否刪除。

![image](https://user-images.githubusercontent.com/1680868/56632188-2a704980-668b-11e9-9ada-6f30e5892a93.png)

**Comment by kelp404** [comment]
補欄位提供前端實作錯誤提示。
判斷相機位置關聯的 `AnnotationModel.failures`。

<img width="1145" alt="螢幕快照 2019-04-24 下午2 40 46" src="https://user-images.githubusercontent.com/1680868/56637918-690fff00-669f-11e9-9b04-882debe5e9f7.png">

**Comment by dca** [comment]
> 補欄位提供前端實作錯誤提示。
> 判斷相機位置關聯的 `AnnotationModel.failures`。
> 

這個的意思是只要判斷 `AnnotationModel.failures` 裡面的值 dump 出來就好嗎？
那我就把關聯的所有 `AnnotationModel.failures` 組合成 `CameraLocation.failures` (?)

**Comment by cjk-halodule** [comment]
相機位置的 failure 和 annotation 的 failure 應該是不一樣的。除了 aggregate annotation 的 failure 以外，需要一些判斷。請參考 https://github.com/TaiBIF/camera-trap-api/issues/79#issuecomment-486542652

**Comment by cjk-halodule** [comment]
看起來這支當中有多個功能需要討論，請先移到 #79 。

**Comment by kelp404** [comment]
> 這個的意思是只要判斷 `AnnotationModel.failures` 裡面的值 dump 出來就好嗎？
> 那我就把關聯的所有 `AnnotationModel.failures` 組合成 `CameraLocation.failures` (?)

count AnnotationModel.failures[0] 存在的數量就好，camera location 不需要知道有什麼錯誤。

**Comment by cjk-halodule** [comment]
這樣的話，我就在 #79 說明其它 annotation.failure 需要實作的計算了。

**Comment by dca** [comment]
@kelp404  另外我發現 aggregate 出來沒有 .dump 可以用，這個問題需要解嗎

**Comment by kelp404** [comment]
> @kelp404 另外我發現 aggregate 出來沒有 .dump 可以用，這個問題需要解嗎

什麼意思？

**Comment by dca** [comment]
dump 的問題已經在新的 commit 裡解決了

**Comment by cjk-halodule** [comment]
Verified. Proceed to frontend.
