### ISSUE TITLE
[POST] /files{?type,cameraLocation}

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#120]
Upload files [POST /files{?type,cameraLocation}]
https://cameratraptw.docs.apiary.io/#/reference/files

**Comment by kelp404** [comment]
未實作：
+ Issue attachment
+ csv, images in ZIP

**Comment by cjk-halodule** [comment]
這個 issue 算完成可由前端實作上傳了？

**Comment by cjk-halodule** [comment]
Proceed to frontend. Related to https://github.com/TaiBIF/camera-trap-vueapp/issues/59

**Comment by cjk-halodule** [comment]
The current output is
```
{
  "id": "5cd6d80d99580e362b7fef0f",
  "type": "annotation-csv",
  "originalFilename": "HL011B-trimmed.csv",
  "filename": "5cd6d80d99580e362b7fef0f.csv",
  "size": 96732
}
```
Would be useful to include the associated uploadSessionId.

**Comment by cjk-halodule** [comment]
uploadSessionId included.

**Comment by kelp404** [comment]
檔案上傳邏輯修改，加入檔名判斷資料是否重複。
<img width="1027" alt="螢幕快照 2019-05-17 上午11 21 45" src="https://user-images.githubusercontent.com/1680868/57901085-0d97f200-7896-11e9-9a09-404a8c24acd4.png">
