### ISSUE TITLE
[GET] project/location-month-retrieved-num 影像回收狀況 (特定年度特定計畫)

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#121]
需要與此功能相等的 endpoint.
https://github.com/TaiBIF/camera-trap-api/wiki/retrieval-status

Dependant: https://github.com/TaiBIF/camera-trap-vueapp/issues/80

**Comment by kelp404** [comment]
前端在畫面呈現時有分成三個維度，舊有 API 無法讓前端方便使用，需要思考新的做法。
合併到 #130
