### ISSUE TITLE
相機位置資料異常回報 WF 2.10.1

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#123]
需要有與此功能等同的 endpoint
https://github.com/TaiBIF/camera-trap-api/wiki/abnormal-data-bulk-replace

Related to: https://github.com/TaiBIF/camera-trap-vueapp/issues/81

**Comment by kelp404** [comment]
<img width="1144" alt="螢幕快照 2019-04-28 上午9 53 00" src="https://user-images.githubusercontent.com/1680868/56857078-6d883080-699b-11e9-85e7-31c5110c276d.png">

**Comment by cjk-halodule** [comment]
@kelp404 
此處是否需要：
- [ ] 定義 /src/models; 其中 abnormality 是要獨立的 collection 還是 attach 在 camera-location 物件中？
- [ ] 根據 model 新增一個 /src/forms/camera-location/camera-locations-abnormality-form.js
- [ ] 及 API spec

**Comment by f2ejack** [comment]
- [ ] 5/6: 新增 /src/models/data/abnormal-camera-location-model.js (因為同一個相機位置的異常狀況會因時間不同而有多筆資料的可能, 所以還是維持單獨的 model)
- [ ] 5/6: 新增 /src/forms/abnormal-camera-location/abnormal-camera-location-form.js
- [ ] 5/7: 新增 /src/handlers/abnormal-camera-location-handler.js (in progress)
- [ ] 5/8: 測試 API
- [ ] 5/8: 撰寫 API spec

**Comment by f2ejack** [comment]
@cjk-halodule 
<img width="871" alt="螢幕快照 2019-05-09 上午6 37 44" src="https://user-images.githubusercontent.com/9169534/57413095-8b6c5580-7225-11e9-883e-2e3281d65885.png">
這裡的"樣區, 子樣區及相機位置"三個資訊是自動帶入的, 那麼是否應該修改為不可更改的呈現方式?

**Comment by cjk-halodule** [comment]
Related to: TaiBIF/camera-trap-vueapp/issues/123

**Comment by f2ejack** [comment]
Writing API file

**Comment by f2ejack** [comment]
Completed API spec.: https://cameratraptw.docs.apiary.io/#/reference/projects/abnormal-camera

**Comment by cjk-halodule** [comment]
缺 notification type = cameraLocationAbnormality

**Comment by cjk-halodule** [comment]
剛送出了一筆相機異常回報：
```
﻿﻿{ 
    "_id" : ObjectId("5cdd577188f14187f29c5d45"), 
    "responseStatus" : NumberInt(200), 
    "hostname" : "ip-10-0-2-229.ap-northeast-1.compute.internal", 
    "user" : ObjectId("5cd662cc99580e21fa7fe0e2"), 
    "ip" : "140.109.29.227", 
    "method" : "POST", 
    "path" : "/api/v1/projects/5cd8c9958c607d84ddade314/camera-location-abnormality", 
    "headers" : "{\"accept-language\":\"en-GB,en-US;q=0.9,en;q=0.8,zh-TW;q=0.7,zh;q=0.6\",\"accept-encoding\":\"gzip, deflate, br\",\"referer\":\"https://dev.camera-trap.tw/project/5cd8c9958c607d84ddade314/info/video/5cd8ca7b8c607d5879ade340/receive\",\"accept\":\"*/*\",\"content-type\":\"application/json; charset=utf-8\",\"user-agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36\",\"origin\":\"https://dev.camera-trap.tw\",\"access-control-allow-origin\":\"*\",\"content-length\":\"201\",\"x-amzn-trace-id\":\"Root=1-5cdd5771-10b08620cad32bba720db3bc\",\"host\":\"api-dev.camera-trap.tw\",\"x-forwarded-port\":\"443\",\"x-forwarded-proto\":\"https\",\"x-forwarded-for\":\"140.109.29.227\"}", 
    "requestBody" : "{\"cameraLocation\":\"5cd8f7b58c607d0746ade734\",\"abnormalityStartDate\":\"2017-04-30T16:00:00.000Z\",\"abnormalityEndDate\":\"2017-05-30T16:00:00.000Z\",\"abnormalityType\":\"others\",\"note\":\"資料似未回收？\"}", 
    "createTime" : ISODate("2019-05-16T12:28:33.180+0000"), 
    "updateTime" : ISODate("2019-05-16T12:28:33.221+0000"), 
    "__v" : NumberInt(1), 
    "processTime" : NumberInt(40)
}
```
但 collection 是空的：
![Screenshot 2019-05-16 20 38 52](https://user-images.githubusercontent.com/31983251/57854351-a426cd80-781a-11e9-8dfc-e1df96ec650c.png)

**Comment by kelp404** [comment]
我有改 collection name 從 `CameraLocationAbnormality` 改成 `CameraLocationAbnormalities`。

**Comment by cjk-halodule** [comment]
對喔 - 那我應該把 endpoints 也都一起改複數..
