### ISSUE TITLE
影片上傳至 YouTube

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#128]
[上一個版本](https://github.com/TaiBIF/camera-trap/tree/master/lambda-youtube-uploader)的流程是：
1. 前端 webapp 直接上傳 zip 後的影片到 S3
2. 自動驅動 lambda 利用 YouTube API 上傳至 YouTube.

先前 lambda 出現錯誤訊息，東西丟不上去。查了youtube api 討論區，瞭解到有 24hrs 內 50 支影片的限制或存取次數上限（2000 點消費點）。故實作時應可控制 queue 的行程在此限制之內接續上傳。

(CC'ed @melissa0520 @lyh-yihsuan )

**Comment by cjk-halodule** [comment]
- [ ] 需要瞭解消費點數計算方式，例如以影像檔的平均大小一個檔案會用掉多少消費點。 @melissa0520 
- [ ] 上傳排程設計，完成所有檔案上傳需要花費的時間。

**Comment by melissa0520** [comment]
> * [ ]  需要瞭解消費點數計算方式，例如以影像檔的平均大小一個檔案會用掉多少消費點。 @melissa0520

google客服說youtube沒有任何客服電話（說他們很難找），在亞洲也沒有任何部門，所以給了我美國的版權部門的email和傳真，我再思考一下怎麼整理成英文詢問
P.S. 客服也說我們的問題沒有直接相關的部門可以回答，比較接近的可能是版權部門（針對大量程式化上傳影片被鎖的情形，總共只有三個部門：舉報、版權、法律）

另外，這是youtube的api資源網站，可能可以先參考看看
https://www.youtube.com/intl/zh-TW/yt/dev/api-resources/

**Comment by kelp404** [comment]
討論中提到一天僅能上傳 50 部影片，預計用 cron job 的方式上傳至 youtube。
會將 cron job 的程式寫到 task-worker.js 中，不獨立再開一個 cron-job.js，因為 cron-job 的負載會非常低，多跑一個 instance 太浪費。。

**Comment by melissa0520** [comment]
@kelp404 
之前使用的youtube api是Data API - videos.insert （用python寫的），我打算詢問官方是否能以程式化方式透過這個API上傳，並不受一天50不影片的限制，有沒有什麼資訊還可以提供讓官方更清楚我們的狀況呢?

**Comment by cjk-halodule** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [影片上傳服務選擇及流程確認](https://trello.com/c/hxrGACFn/57-%E5%BD%B1%E7%89%87%E4%B8%8A%E5%82%B3%E6%9C%8D%E5%8B%99%E9%81%B8%E6%93%87%E5%8F%8A%E6%B5%81%E7%A8%8B%E7%A2%BA%E8%AA%8D)

**Comment by kelp404** [comment]
我傳了 12M 的檔案 16 次之後就超過限制了，要跟 google 要求更高點數還是找其他服務？

https://console.developers.google.com/iam-admin/quotas?project=taibif-youbute
<img width="1315" alt="螢幕快照 2019-05-08 下午6 26 09" src="https://user-images.githubusercontent.com/1680868/57369377-f4b97d80-71bf-11e9-98b0-5fdc90c8c0b7.png">

**Comment by cjk-halodule** [comment]
我們來試看看 Vimeo?

**Comment by kelp404** [comment]
晚點試，我覺得這一定得付錢。
自己做的話現在來不及了，除非規定使用者自行轉成 mp4。

**Comment by cjk-halodule** [comment]
付費的話是 ok 的

**Comment by f2ejack** [comment]
如果透過GCP的"付費方案"與銷售人員聯繫是否可以得到答案呢？
https://cloud.google.com/contact/

Jack

Kelp <notifications@github.com> 於 2019年5月8日 週三 下午6:40 寫道：

**Comment by cjk-halodule** [comment]
@f2ejack 也許請 @melissa0520 從這個方向去問會有進展。

**Comment by melissa0520** [comment]
我沒有找到官網關於消費點數的說明，不過還有看到影片單個上傳最大容量為128GB
然後找到可能解決方案如下，但需要各位協助確認是否可以解決：

1. [Data API的配額調整](https://console.developers.google.com/iam-admin/quotas?project=durable-micron-240015&supportedpurview=project)，可以在購買Google cloud platform方案後提高配額（如第二點連結）
2. [Google cloud platform的各式方案](https://cloud.google.com/free/?_ga=2.111592647.-238490282.1556712353)，其中有幾個我覺得有可能可以試試看（如Google cloud functions ?)

**Comment by kelp404** [comment]
另外還有一個問題就是 oauth 登入。
昨天試著用 `service_account` 直接傳影片，一直傳不上去。網路上有人提到一定要用 oauth。
https://stackoverflow.com/questions/25803937/video-upload-using-youtube-google-api-directly-from-server-using-node-js

我用官方的工具拿到的 token 一小時後就會過期，要不停的去更新。
如果真的用這種方式驗證的話變成要做一個後台讓管理者輸入 youtube 的帳密，而且如果伺服器出問題停機超過一小時，管理者必須再去後台登入 youtube。

我今天會去查看看其他的服務。

**Comment by melissa0520** [comment]
> 另外還有一個問題就是 oauth 登入。
> 昨天試著用 `service_account` 直接傳影片，一直傳不上去。網路上有人提到一定要用 oauth。
> https://stackoverflow.com/questions/25803937/video-upload-using-youtube-google-api-directly-from-server-using-node-js
> 
> 我用官方的工具拿到的 token 一小時後就會過期，要不停的去更新。
> 如果真的用這種方式驗證的話變成要做一個後台讓管理者輸入 youtube 的帳密，而且如果伺服器出問題停機超過一小時，管理者必須再去後台登入 youtube。
> 
Google 那邊要跟我約時間電話討論，我預計約今天下午，也會把這件事跟他提

**Comment by melissa0520** [comment]
請問我們這邊上傳影片的速度是多少？

**Comment by cjk-halodule** [comment]
範例資料夾已分享。
我沒有辦法從 console 讀上面的任務摘要說。

請使用 https://aws.amazon.com/mediaconvert/pricing/
avc codec SD 1pass 30-60 fps 試看看

**Comment by kelp404** [comment]
原檔會保留，轉出來的是要在瀏覽器上直接播放的，我覺得 30fps 就足夠了。
+ 30fps 檔案會比較小。
+ 原始檔可能不會全部都是 60fps。
+ 16fps 人眼就會覺得是動畫了，遊戲需要 60fps 是因為要回饋使用者的操作。

解析度 SD（720 × 480）確定夠嗎？

**Comment by cjk-halodule** [comment]
那就是 avc codec HD 1pass 30fps

**Comment by kelp404** [comment]
@cjk-halodule

1. 影片的副檔名接受 `mov`, `avi`, `mp4` 這些對嗎？wireframe 找不到
2. 如果上傳單一影片的話，產生出來的 `annotation` 時間怎麼設？（圖片的話是從 exif）
3. 之前討論的時候說過影片的使用情境是「看著影片然後加 annotation 並且標記時間」。
  但是我們 annotation 的編輯界面中 `時間` 是不可動的，這部分沒問題嗎？

目前時間是必填欄位。
https://github.com/TaiBIF/camera-trap-api/blob/8d1747c34322ad9b7446f0d8a6a97ea027b91c2a/src/models/data/annotation-model.js#L79-L86

**Comment by cjk-halodule** [comment]
1. 還有多幾個，全部是 AVI JPG M4V MP4 MOV MP3 => 我會補到 WF 中。
2. 影片時間是算它的開始時間 EXIF 內有 kMDItemContentCreationDate         = 2019-05-03 06:55:16 +0000
3. 時間不用考慮影片長度，就令其不可動。

**Comment by cjk-halodule** [comment]
剛看了一下：
kMDItemFSContentChangeDate         = 2018-03-30 02:34:26 +0000
kMDItemContentModificationDate     = 2018-03-30 02:34:26 +0000
這兩個欄位應該才是要參考的，kMDItemContentCreationDate 看來是檔案在送到台北來之前複製的時間。


[mp4-EXIF.csv.gz](https://github.com/TaiBIF/camera-trap-api/files/3166206/mp4-EXIF.csv.gz)

**Comment by kelp404** [comment]
> 1. 還有多幾個，全部是 AVI JPG M4V MP4 MOV MP3 => 我會補到 WF 中。

`JPG`, `MP3`？

**Comment by cjk-halodule** [comment]
對不起，JPG 是打錯了，MP3 是和影像放在一起，所以想說即使沒有視訊也可以撥，但如果沒有辦法處理，就先不把 MP3 放進去。

**Comment by kelp404** [comment]
MediaConver 在轉換時會需要指定影像跟聲音，有一個錯誤的話就無法轉換。
建議下階段在支援 mp3。

**Comment by kelp404** [comment]
ref:
https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified

**Comment by cjk-halodule** [comment]
Verified.
