### ISSUE TITLE
計畫已辨識物種

### ISSUE THREAD

**Issue by oahehc** [TaiBIF/camera-trap-api#129]
Reference: https://github.com/TaiBIF/camera-trap-api/wiki/image-species-group
Relate to: https://github.com/TaiBIF/camera-trap-vueapp/issues/82

![image](https://user-images.githubusercontent.com/13633490/56846619-ee93e900-6903-11e9-8dc5-fa799ebbec39.png)

**Comment by kelp404** [comment]
<img width="1200" alt="螢幕快照 2019-04-28 上午10 03 25" src="https://user-images.githubusercontent.com/1680868/56857160-e340cc00-699c-11e9-8dc4-41de7db1cbc0.png">

**Comment by cjk-halodule** [comment]
此處做法為利用 annotation api ```annotations{?studyArea,cameraLocations,startTime,endTime,index,size,sort}``` 取得計畫所有資料後 "group by" species, 扣除「測試」、「空拍」、「無」等非真實物種的比數後，計算傳回的百分比。回傳結果應該要包含 id 等資料，以便前端形成連結，讓圓餅圖塊可以連到計畫資料。

**Comment by cjk-halodule** [comment]
參考輸出
```
{
      "species_group": [
        {
          "species": "松鼠",
          "count": 3
        },
        {
          "species": "獼猴",
          "count": 63
        },
        {
          "species": "食蟹獴",
          "count": 3
        },
        {
          "species": "無法辨識",
          "count": 3
        },
        ...,
        {
          "species": "鼬獾",
          "count": 150
        }
      ],
      "total": 1895,
      "modified": 1542014476.298
    }
```

**Comment by dca** [comment]
還需要按照月份分組

> 參考輸出
>

**Comment by kelp404** [comment]
物種的 collection 會再調整，今天會送上去。

**Comment by cjk-halodule** [comment]
可有：
- [ ] 一個物種在整個計畫的計數
- [ ] 附加此物種在計畫期間每月的辨識數量。此項為下階段進行。 
- [ ] 附加此物種在各樣區的辨識數量。此項為下階段. (WF 2.11.3) 

另外， @dca  修正上面說明：
```
扣除「測試」、「空拍」、「無」等非真實物種的比數後，計算傳回的百分比
```
為
```
傳回計數，按數量排序（百分比由前端處理）
```

@oahehc  若有任何格式的建議和問題請提出囉。
