### ISSUE TITLE
wf 2.6~2.9 影像回收/辨識狀況

### ISSUE THREAD

**Issue by kelp404** [TaiBIF/camera-trap-api#130]
@kelp404 前端在畫面呈現時有分成三個維度，舊有 API 無法讓前端方便使用，需要思考新的做法。

<img width="1204" alt="螢幕快照 2019-04-28 上午10 12 56" src="https://user-images.githubusercontent.com/1680868/56857303-539c1d00-699e-11e9-9c6d-c6fe793f2fda.png">
<img width="1199" alt="螢幕快照 2019-04-28 上午10 13 11" src="https://user-images.githubusercontent.com/1680868/56857302-539c1d00-699e-11e9-8bec-925a231c1cf9.png">
<img width="1198" alt="螢幕快照 2019-04-28 上午10 13 24" src="https://user-images.githubusercontent.com/1680868/56857301-53038680-699e-11e9-911a-2b5fa1c7e5b2.png">
<img width="1175" alt="螢幕快照 2019-04-28 上午10 13 35" src="https://user-images.githubusercontent.com/1680868/56857300-53038680-699e-11e9-9a18-c1aaf0496834.png">

https://github.com/TaiBIF/camera-trap-vueapp/issues/80

---
前端呈現時有分成三個維度
![56815558-3b2fe380-6874-11e9-9243-c96ee6658947](https://user-images.githubusercontent.com/1680868/56857556-872c7680-69a1-11e9-925c-5e0426ade418.png)

**Comment by kelp404** [comment]
@cjk-halodule 資料呈現上有問題：

wf 2.8 顯示每月資料筆數時呈現相機失竊資料的問題
<img width="1132" alt="螢幕快照 2019-04-28 上午10 16 42" src="https://user-images.githubusercontent.com/1680868/56857344-ec329d00-699e-11e9-9af5-a078ecc577f1.png">
假如某個月份我透過「相機異常回報」功能將五月回報為相機失竊，整個五月都沒有資料。
在左圖的時候我只要在該相機位置的五月用紅色區塊呈現就可以。
但在右圖我是沒有資料筆數的，這樣沒問題嗎？

**Comment by cjk-halodule** [comment]
是的。Wireframe 兩張圖的邏輯沒對上，PT03A 在左圖應該要畫成1-4月綠色，5月紅色。

**Comment by cjk-halodule** [comment]
1. 如何判定使用者已經走過一筆資料並確認資料的鑑定狀態，即使物種名稱不在預設中（看到才發現有拍到的新紀錄物種）？ => 需要新欄位？ 
2. 上傳 CSV 的物種欄位若有資料是否視為已辨識？
3. 是否需要與預設物種名單核對？

**Comment by kelp404** [comment]
1.
資料會在上傳 csv 的時候填上去。
當 csv 的物種不在計畫中會自動新增物種，然後這次上傳所產生的標註只要用了這個物種就會有 `new-species` 紀錄。
https://github.com/TaiBIF/camera-trap-api/blob/454e752c7bd160faf32870519da03b9d95a2fda8/src/models/const/annotation-failure-type.js#L2
https://github.com/TaiBIF/camera-trap-api/blob/454e752c7bd160faf32870519da03b9d95a2fda8/src/models/data/annotation-model.js#L54-L64

3.
每個計畫都有定義所有物種。
https://github.com/TaiBIF/camera-trap-api/blob/454e752c7bd160faf32870519da03b9d95a2fda8/src/models/data/species-model.js#L7-L46

**Comment by dca** [comment]
- [x] Case 1. All StadyArea (包含底下子項目)
- [ ] Case 2. single StadyArea
- [ ] Case 3. single camara
- [ ] 支援按照時間區間查詢

**Comment by dca** [comment]
參考的 response 格式大概長這樣，只有 _id 裡面的欄位不同，需不需要幫前端做什麼整理，還是前端再另外處理？


``` json
[
    {
        "_id": {
            "month": 3,
            "year": 2019,
            "cameraLocation": "5cd6648799580eda3c7fe12c"
        },
        "dataCount": 136,
        "fileCount": 136,
        "speciesCount": 136,
        "failures": 0,
        "lastData": "2019-05-11T06:55:55.508Z"
    },
    {
        "_id": {
            "month": 6,
            "year": 2018,
            "cameraLocation": "5cd6648799580eda3c7fe12c"
        },
        "dataCount": 2074,
        "fileCount": 2074,
        "speciesCount": 2074,
        "failures": 120,
        "lastData": "2019-05-11T06:43:38.407Z"
    },
    {
        "_id": {
            "month": 7,
            "year": 2018,
            "cameraLocation": "5cd6648799580eda3c7fe12c"
        },
        "dataCount": 2342,
        "fileCount": 2342,
        "speciesCount": 2342,
        "failures": 12,
        "lastData": "2019-05-11T06:46:11.711Z"
    }
]
```

**Comment by cjk-halodule** [comment]
spec 中還有一個最後更新時間，如果是即時算的就可以用當下的時間，如果是事先算的就要記最近一次算的時間了。

**Comment by cjk-halodule** [comment]
timeUpdated added in 5859e4ae566de7d211f6154df3aa9835b7a0cb1e.
