### ISSUE TITLE
CSV 上傳欄位格式確認

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#131]
目前發現舊有的資料 CSV 格式無法上傳的問題（當然囉），需要釐清的是：

- [ ] 後端 API 的欄位檢核如何進行
- [ ] 欄位對不到應該要有錯誤訊息給前端，向使用者說明。這部分和錯誤回報有關？
- [ ] API 文件應該補充相關說明文字

[HC20A_test.csv.zip](https://github.com/TaiBIF/camera-trap-api/files/3124629/HC20A_test.csv.zip)

**Comment by kelp404** [comment]
1. 欄位檢核的邏輯是依據規格書上的流程圖。
  欄位的資料定義是依照順序決定，與第一行的標頭無關。
  會用順序決定是因為在重構前標頭非常的混亂，而且未來還要支援多國語系，重構前下載範本取得的標頭是中文的，但上傳用的範例檔有些是英文的。
  例如第一欄就代表樣區，第二欄子樣區...
2. 所有的問題都會更新在 upload session 中。
3. 會拆散到 upload session 的 API 中。

我用來測試的 csv：
```
樣區,子樣區,相機位置,檔名,時間,物種,年齡
title,titleX,PT02B,IMG_7191.JPG,2017-11-09 11:48:46,,成體
```

問題：
1. 要加入 `project` 欄位嗎？
  HC20A_test.csv.zip 的第一欄是 `project`，但在重構前的程式並沒有 `project` 這個欄位，所以目前的程式也沒有 `project`。
2. 空值確定要用 `NA` 表示嗎？
  重構前的程式是直接用空字串表示，csv 上就是一個空格不會有東西，但在 HC20A_test.csv.zip 是用 `NA` 表示空值。如果用 `NA` 表示空值的話，使用者到時候真的不能有值是 `NA`。

**Comment by cjk-halodule** [comment]
Project 不用。資料上傳時即已選定。
空值不用 NA, 感覺會有麻煩。

**Comment by cjk-halodule** [comment]
目前 CSV 的欄位確認會根據計畫設定中的 data-fields 嗎？

**Comment by cjk-halodule** [comment]
想知道像是有些計畫已經有 sex,lifeStage,id,category,sciName,behavior 等欄位資訊在系統上應該如何設定才能在不用編輯太多的情況下上傳？
另外目前的樣區、子樣區已經不再限制固定兩個欄位，那麼目前資料中的 site, subSite 應如何處理？

**Comment by kelp404** [comment]
> 目前 CSV 的欄位確認會根據計畫設定中的 data-fields 嗎？

會

**Comment by kelp404** [comment]
> 想知道像是有些計畫已經有 sex,lifeStage,id,category,sciName,behavior 等欄位資訊在系統上應該如何設定才能在不用編輯太多的情況下上傳？
> 另外目前的樣區、子樣區已經不再限制固定兩個欄位，那麼目前資料中的 site, subSite 應如何處理？

申請新欄位然後把狀態改成 `approved`。
https://cameratraptw.docs.apiary.io/#/reference/data-fields/apply-for-a-new-data-field/apply-for-a-new-data-field/200?mc=reference%2Fdata-fields%2Fapply-for-a-new-data-field%2Fapply-for-a-new-data-field%2F200

樣區是第一欄，子樣區是第二欄，資料只有只有一層樣區的話不要填子樣區（第二欄）。

**Comment by cjk-halodule** [comment]
```資料只有只有一層樣區的話不要填子樣區（第二欄）``` 確認一下，也就是連空值```,""```不會有？

**Comment by kelp404** [comment]
> `資料只有只有一層樣區的話不要填子樣區（第二欄）` 確認一下，也就是連空值`,""`不會有？
> 
> Related to #151.

填寫空字串。
```
樣區,子樣區,相機位置,檔名,時間,物種,年齡
title,,PT02B,IMG_7191.JPG,2017-11-09 11:48:46,,成體
```

**Comment by cjk-halodule** [comment]
瞭解，感謝！

**Comment by cjk-halodule** [comment]
@kelp404 抱歉再確認一下 樣區,子樣區,相機位置,物種,年齡  等系統都是會自動對既有的名稱嗎？ （好像有問過）

**Comment by kelp404** [comment]
依據欄位順序確認內容的，所以在匯入的時候第一行的資料填什麼都沒關係。

**Comment by cjk-halodule** [comment]
我的意思是 像
```花蓮處  HL09B   IMG_0233.JPG    2016-01-28 12:56:04     山羌```
這樣的一筆資料 中間的中文值像樣區名稱會自動對應到 5cd26d5252ee1a39d17fdc66
相機位置會對到 5cd29c2f52ee1a06867fe015
是嗎？

**Comment by kelp404** [comment]
會

**Comment by cjk-halodule** [comment]
讚，另外，若該行的欄位數量超過已定義的欄位數，多餘的是不處理嗎？

**Comment by kelp404** [comment]
要查了才知道會發生什麼事，格式要統一
