### ISSUE TITLE
新增單筆資料的 API

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#132]
目前 annotation 有 search 和 update 的 endpoint, 在 檔案上傳之外，似乎沒有新增單筆的 endpoint，而 update 必須要有 annotationId 才行。因為使用者在前端有可能完全在系統上新建所有資料（無既有之 CSV 檔），故應該需要一個 endpoint 來處理單筆新建的需求。

**Comment by kelp404** [comment]
我覺得用 csv 上傳就好，因為目前規格上並沒有這個功能，開這個 API 的話需要付出不少成本：
+ 邏輯需與檔案上傳同步
  新增標註的邏輯其實很複雜，要判斷是否重複、檢查欄位...等。

**Comment by cjk-halodule** [comment]
不好意思，現在才發現這件事在 WF 上並不明確。資料不會只有 CSV 上傳，而有可能在前端一筆一筆建置。一個確認的問題是：目前的 API 可以複製一列貼上嗎？

**Comment by kelp404** [comment]
原來如此，複製的功能的確需要加開新增標註的 API。

**Comment by cjk-halodule** [comment]
還有一個編輯需求是一張照片如果有三隻動物，原本的一筆資料（3隻）會需要分成三筆，所以資料庫才會知道有三隻。這是為了單純化個體數的計算。

找時間說明這些編輯的需求？我相信有相當 csv import 的邏輯是可以共用的。+

**Comment by kelp404** [comment]
我先做新增 annotation 的 API，弄完再去處理影片問題。

**Comment by cjk-halodule** [comment]
目前這個新增的功能會檢查檔案（但文件中沒列 required），但如果前端的紀錄尚無與檔案連結，此時複製就有可能會被擋下來。可否移除這個限制？

(P.S. 它還會檢查檔案的計畫和相機位置的計畫是不一樣的，害我驗不下去 XD)

**Comment by kelp404** [comment]
`.file` 是 optional，`.filename` 才是 required。
確實會檢查有沒有用了其他計畫的檔案，但使用者的操作會是在同計畫底下才對，這個確定不驗嗎？

<img width="845" alt="螢幕快照 2019-05-17 下午1 12 08" src="https://user-images.githubusercontent.com/1680868/57904600-fd880e80-78a5-11e9-9268-27d2d8250ab6.png">

**Comment by cjk-halodule** [comment]
確定喔 因為有可能該筆資料尚未有任何檔案連結

**Comment by kelp404** [comment]
連檔名都沒有嗎？

**Comment by cjk-halodule** [comment]
對的 這是只有資料複製的情況

**Comment by cjk-halodule** [comment]
這樣的話還是預期透過上傳流程解決 也就是先上傳照片再下載 csv 的情況 這樣就應該都一定會有檔名，也就不會有我這裡提到的顧慮了。
