### ISSUE TITLE
4.13.2 點擊放大

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#14]
Define path for both preview and large image file.
Related to TaiBIF/camera-trap-webapp#40

**Comment by trashmai** [comment]
請參考 [API文件 WF 4.2](https://github.com/TaiBIF/camera-trap-api/wiki/API-Documentation#%E8%B3%87%E6%96%99%E7%AF%A9%E9%81%B8-wf-42) 最近的更新。

在 post data 下的 projection 與 response 裡面加入了 low_quality_url 這個新屬性。

Preview image path 請用 low_quality_url。
Large image path 請用 url。
網址組成的前綴暫時改成 `https://s3-ap-northeast-1.amazonaws.com/camera-trap/`

**Comment by diabloevagto** [comment]
目前沒看到這個欄位，是否已經部署？

**Comment by cjk-halodule** [comment]
@trashmai 請將相關的 commit checksum 貼過來？
