### ISSUE TITLE
study-area 需要增加 lock, error 資訊

### ISSUE THREAD

**Issue by oahehc** [TaiBIF/camera-trap-api#143]
![image](https://user-images.githubusercontent.com/13633490/57079625-504cbc80-6d23-11e9-92e9-92f98322b7a6.png)

relate to: https://github.com/TaiBIF/camera-trap-vueapp/issues/79

**Comment by kelp404** [comment]
錯誤數量：`failures`
https://github.com/TaiBIF/camera-trap-api/commit/0a6f7d27b3ffc5ba2a82d16d89873bdaf6574b1f

lock 是跟 camera location 的，尚未實作。

**Comment by cjk-halodule** [comment]
Related to: https://github.com/TaiBIF/camera-trap-api/issues/109

**Comment by kelp404** [comment]
<img width="1156" alt="螢幕快照 2019-05-02 下午10 11 06" src="https://user-images.githubusercontent.com/1680868/57081407-344b1a00-6d27-11e9-9317-835f21cb2fe4.png">

**Comment by cjk-halodule** [comment]
failures and isLocked verified.
