### ISSUE TITLE
[POST] /data-fields/{dataFieldId}/_approve, _reject, _cancel

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#149]
Related to #147 
@oahehc : 系統管理員 需要有一個 endpoint 送 _approve, _reject, _cancel 操作

Q1. API 缺 projectId / projectName
 - 欄位的申請是供所有計畫使用，故應不需要 projectId. /projects/{projectId} 會列出加入的欄位

Q2. Endpoint page design
 - http status code 204 應足夠

**Comment by oahehc** [comment]
SPEC: data-field-application => 系統管理員 需要有一個 endpoint 送 _approved, _reject, _cancel 操作
Wireframe: 
![image](https://user-images.githubusercontent.com/13633490/57191214-883b4600-6f55-11e9-90ac-48039dd5e95c.png)

Q1: 但 WF 畫面需要顯示計畫名稱與連結, 如果不應該顯示就是 WF 要調整?
Q2: 這邊指的是操作 approved/reject/cancel 的畫面, 點擊檢視應該要跳轉到該頁面, 目前似乎沒在 WF 看到?

**Comment by kelp404** [comment]
我覺得先實作 _approve, _reject 就夠了，讓開發時可以用 API 改資料欄位的狀態。
因為這些功能都不在規格中，尤其是使用者提出申請後還要能取消，這個 UI 至少要多出一頁。

**Comment by cjk-halodule** [comment]
Verified.
