### ISSUE TITLE
4.17 錯誤提示格式

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#15]
- [x] 物種不在預設中
- [x] 在文件中標示如何儲存錯誤提示。
~- [ ] 相片時間不合理~
~- [ ] 檔名不連續~
~- [ ] 相機疑似異常~
~- [ ] 偵測到非3連拍，請注意相機狀況或設定~

Related to TaiBIF/camera-trap-webapp#44

**Comment by cjk-halodule** [comment]
From @kelp404 : 
<img width="928" alt="2018-11-25 8 53 56" src="https://user-images.githubusercontent.com/31983251/48974378-b86ee680-f091-11e8-82dd-cc666e147ca1.png">

目前我看到記錄錯誤的欄位都是 bool
MultimediaAnnotation.multimedia_error_flag, MultimediaAnnotation.tokens[0].token_error_flag。
我覺得錯誤提示可由前端決定內容。
1. 輸入框是沒有驗證邏輯的
2. 時間欄位 - 格式錯誤
3. 下拉選單 - 不在選項中

**Comment by cjk-halodule** [comment]
目前除了 bool 外，api 有沒有前端有沒有可以判定是那類型錯誤的資訊?
2. @diabloevagto 時間欄位格式前端應該改為 yyyy-mm-dd hh:mm；到時後端資料以 timestamp 存
3. 請確認前端有選項，然後後端設定也有得存

**Comment by kelp404** [comment]
依據欄位資料型態判斷，時間就只有一種格式錯誤的提示，下拉選單也只有一種不在選項內的提示。
樣區欄位 Project.adminArea
相機欄位 Project.cameraLocations
物種欄位 Project.speciesList
其餘自訂欄位 DataFieldAvailable.widget_select_options

根據我的了解，目前資料異動的方式有兩個「csv 上傳」跟「直接編輯」。
csv 上傳如果格式錯誤的話會被要求重新上傳。
<img width="1042" alt="2018-11-25 9 25 53" src="https://user-images.githubusercontent.com/1680868/48974426-26b4a880-f094-11e8-85d8-6d473fae3b73.png">

直接編輯的話（使用時間選取的元件、下拉選單）不會出現輸入錯誤內容的問題。
我覺會出現錯誤的可能只有 csv 上傳後去修改專案的欄位，如物種選項。

**Comment by diabloevagto** [comment]
這是在討論什麼？
4.17 並沒有上面幾個截圖

另外時間傳給後端要傳什麼都可以，看 api 怎麼定義

**Comment by kelp404** [comment]
<img width="1138" alt="2018-11-25 11 41 10" src="https://user-images.githubusercontent.com/1680868/48975230-13f79f00-f0a7-11e8-823c-f150d280aad4.png">

這條 issue 指的應該是要能讓前端完成我圈起來的錯誤提示對吧？

如果是錯誤提示的話我覺得前端可以從其他欄位決定提示內容「物種名稱不在預設中，請修正名稱，或回報管理員。」。
只要判斷 MultimediaAnnotation.tokens[0].token_error_flag 就知道錯誤，再從 MultimediaAnnotation.tokens[0].key 去判斷資料型態即可。
每種資料型態只會有一種錯誤訊息。

**Comment by diabloevagto** [comment]
@kelp404 除了你圈起來以外其他全都要提供
a 側邊⽬目錄_錯誤提⽰
b 相機位置_錯誤提⽰示
c 編輯模式_錯誤提⽰示

另外錯誤狀況有好幾種如果都可以從前端判斷那我在自己判斷，不過目前並沒有你提到的 `MultimediaAnnotation`
1. 物種不在預設中
2. 相片時間不合理理
3. 檔名不連續
4. 相機疑似異異常 偵測到非3連拍，請注意相機狀狀況或設定

**Comment by kelp404** [comment]
@diabloevagto 
a. 側邊⽬目錄_錯誤提⽰ - 這個會處理 #43 
b 相機位置_錯誤提⽰示 - 這個也會處理 #44

我先把這兩單處理掉

**Comment by kelp404** [comment]
Hello @diabloevagto 
已更新 API 文件 https://github.com/TaiBIF/camera-trap-api/wiki/annotation#%E9%8C%AF%E8%AA%A4%E6%8F%90%E7%A4%BA-wf-417

a 側邊⽬目錄_錯誤提⽰
b 相機位置_錯誤提⽰示

**Comment by cjk-halodule** [comment]
#16 的事情看來都在這裡進行，所以關掉。請 @kelp404 再看看我移過來的 item list 完成狀況喔。謝謝。

**Comment by cjk-halodule** [comment]
現在 編輯模式的錯誤提示還在處理中，對嗎？

**Comment by kelp404** [comment]
c 編輯模式_錯誤提⽰ 11/26 討論結果是：
目前資料庫僅有紀錄 error_flag，沒有錯誤內容。
但下拉選單的錯誤僅有一種可能「輸入內容不在選項中」，所以前端可以自行判斷。

其餘的錯誤在資料匯入時就會匯入失敗或是後端也無法判斷，不會有後續編輯的問題。
- 相片時間不合理理
- 檔名不連續
- 相機疑似異異常 偵測到非3連拍，請注意相機狀狀況或設定

**Comment by cjk-halodule** [comment]
上述三種情況必須得再回頭與需求端再確認，故此票關閉。謝謝 @kelp404 !
