### ISSUE TITLE
新增 API 供單筆 annotation 補齊圖片及影片

### ISSUE THREAD

**Issue by kelp404** [TaiBIF/camera-trap-api#174]
<img width="1387" alt="螢幕快照 2019-05-18 下午3 30 00" src="https://user-images.githubusercontent.com/1680868/57966220-eae30780-7981-11e9-8171-580e969ee832.png">

**Comment by cjk-halodule** [comment]
![Screenshot 2019-05-19 18 20 51](https://user-images.githubusercontent.com/31983251/57980839-e3dff600-7a62-11e9-994a-29c93ecf13ec.png)

那裡有錯了？

**Comment by cjk-halodule** [comment]
Verified. to be implemented at https://github.com/TaiBIF/camera-trap-vueapp/issues/52.
