### ISSUE TITLE
圖片的壓縮需要再一張縮圖供預覽使用

### ISSUE THREAD

**Issue by kelp404** [TaiBIF/camera-trap-api#175]
除了 1280px 的圖片外，再多產一張 640px 的圖片。
https://github.com/TaiBIF/camera-trap-api/blob/76c9701091fca385914d7dc9d5490d6b4e1feb4d/src/models/data/file-model.js#L198-L209

**Comment by cjk-halodule** [comment]
640px? 這支目前好沒有這麼做？

**Comment by kelp404** [comment]
已經部版了
<img width="1254" alt="螢幕快照 2019-05-20 下午8 29 19" src="https://user-images.githubusercontent.com/1680868/58021628-fed36880-7b3d-11e9-951c-a2575f6e17f9.png">
