### ISSUE TITLE
取得 annotation 內容除了原本的 total 總筆數外，需新增個別相機位置的數量

### ISSUE THREAD

**Issue by diabloevagto** [TaiBIF/camera-trap-api#180]
Get an annotation 原本只有給 total 總共的篩選筆數
為了要判斷是否此次刪除 annotation 會讓任意相機位置底下所有 annotation 都被刪除
所以需要加上 `所刪選的每一個相機位置個別有多少筆 annotation`

**Comment by kelp404** [comment]
> Get an annotation 原本只有給 total 總共的篩選筆數

是 `GET /annotations` 還是 `GET /annotations/:annotationId`？

相機位置要的不是只有錯誤提示的數量？
你在刪除 annotation 的時候知道對應的相機位置，應該是有辦法計算。

**Comment by diabloevagto** [comment]
這一個 `GET https://api-dev.camera-trap.tw/api/v1/annotations/{annotationId}`
我取到的資料是分頁不會取得全部資料，所以沒辦法判斷是否能夠刪除

**Comment by kelp404** [comment]
> 該筆資料刪完後會導致該相機位置沒有資料，就不給刪

這個邏輯是為了什麼？

**Comment by cjk-halodule** [comment]
說明一下，這是為了在前端實作刪除時檢查刪完後是否該相機位置的資料會等於 0，若等於零，則刪除功能會灰掉，因此需要知道查詢送出時所涉及相機位置的總筆數。有兩個可能的做法：
1. 前端在送出篩選條件後，根據所包含的相機位置，分別送查詢得知相機位置的資料總筆數
2. 後端在回傳篩選結果時，也同時回傳所涉及相機位置的資料總筆數

至於相機位置的資料為何不能為 0 ，這個 spec 只有記到結論，我還在等主持人回覆再把原因記到既有的文件中。

**Comment by kelp404** [comment]
不能刪最後一筆是為了什麼？
是客製化需求、避免某件事的 workaround？
另外標註是軟刪除。

我覺得主持人也就是顧客應該提出問題，而不是想解決方案，不然很容易做出奇怪的東西。
因為顧客不清楚系統怎麼運作的，在資訊不足的情況下制定解決方案很容易出問題。

**Comment by cjk-halodule** [comment]
同意，這件事等有更多資訊時再推進。

**Comment by cjk-halodule** [comment]
和老師確認過之後，相機位置資料是否為 0 的檢查應不需做，會再修正 WF 上的文字。再麻煩 @diabloevagto 推進了。抱歉釋疑過程中的消耗。😓

**Comment by diabloevagto** [comment]
簡單來說就是直接刪除就好？不需要判斷是否能刪？

**Comment by cjk-halodule** [comment]
對
