### ISSUE TITLE
計畫內物種的時空分布 metrics

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#184]
物種在系統中的時空分布是提供研究人員洞見的重要資訊，目前物種的分布座標基本上是以相機位置的座標表示，我們需要有一個 metrics  API 計算計畫內：

- [x] 整個計畫前五大已辨識物種在計畫期間逐月的資料筆數
- [ ] 個別相機位置的前五大已辨識物種逐月的資料筆數
- [x] 此處的物種以整個計畫的為主，不需再針對相機位置計算該位置的前五大
- [x] 物種只計算計畫中預設物種清單，去除諸如「空拍」、「測試」、「人」、「定時測試」、「工作照」等
- [x] 此 endpoint 的計算不需提供年份的filter

此 feature 支援 https://github.com/TaiBIF/camera-trap-vueapp/issues/182

**Comment by cjk-halodule** [comment]
我在 local 端跑 `http://0.0.0.0:3000/api/v1/projects/5ce75c027575450a9e79b804/study-areas/5ce75c05757545dccc79b84c/species-time-series` 回傳 bad request

**Comment by oahehc** [comment]
看文件跟之前討論的內容有差異
https://github.com/TaiBIF/camera-trap-vueapp/issues/182#issuecomment-496764632
https://github.com/TaiBIF/camera-trap-vueapp/issues/182#issuecomment-496907379
1. 原本是說一次給 project 所有時間的資料而不是 by year call
2. 我認知應該是我傳 projectId 時要給該 project 所有 studyArea 的資料, 我傳 studyAreaId 時要給該 studyArea 所有 cameraLocation 的資料, 目前文件看來是只能 by studyArea or cameraLocation 逐一拿


![image](https://user-images.githubusercontent.com/13633490/58758708-857e4180-8551-11e9-9c86-83cbcbe68b8b.png)

**Comment by dca** [comment]
@oahehc 沒有資料的年月有需要做一個空的 species 出來給你嗎

**Comment by cjk-halodule** [comment]
我猜要 這樣前端的邏輯會乾淨些？

**Comment by oahehc** [comment]
> 沒有資料的年月有需要做一個空的 species 出來給你嗎
Yes, 如果該 studyArea / cameraLocation 在該月份沒有資料最好也能給一個空的 array, 
這樣才不用 loop 完所有資料去找出最小跟最大日期

**Comment by dca** [comment]
@oahehc 如果是這樣的話要不要把資料做成讓你可以直接按照年月取 example: data[2019][1]

```
{
  2018: { 
    1: { ... },
    2: { ... },
    ...
    12: { ... },
  },
  2019: { 
    1: { ... },
    2: { ... },
    ...
    12: { ... },
  }
}

```

**Comment by oahehc** [comment]
前端這邊差不多都實做完了, 所以可以依照原本 format 即可, 感謝。
https://github.com/TaiBIF/camera-trap-vueapp/issues/182#issuecomment-497924250

**Comment by dca** [comment]
推一個會補月份的版本，但如果中間跳年會有問題，待修

https://github.com/TaiBIF/camera-trap-api/commit/eff440299b4c4db2bc2eb6d2ad95ed590b299f33

**Comment by cjk-halodule** [comment]
Spec satisfied.
