### ISSUE TITLE
篩選的 「拍攝時段」功能無效

### ISSUE THREAD

**Issue by moogoo78** [TaiBIF/camera-trap-api#212]
篩選及下載的「拍攝時段」篩選功能網頁顯示無效（顯示全部物種），但下載的資料集有成功篩選。

下載的資料集有成功篩選，但網頁顯示全部物種（即顯示所有資料）

**Comment by cjk-halodule** [comment]
不太確定是否為後端的問題，可否把重現的步驟、網頁送出的 API call 及預期的結果貼在這裡？

**Comment by moogoo78** [comment]
確定是前端的問題, ref: https://github.com/TaiBIF/camera-trap-vueapp/issues/287
