### ISSUE TITLE
3.3 編輯常見物種排序的 API

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#22]
- [x] 說明必須使用的 endpoint 及 JSON 格式

目前似乎是在 [/project/bulk-update](https://github.com/TaiBIF/camera-trap-api/wiki/API-Documentation#update-%E7%89%B9%E5%AE%9A%E6%AC%84%E4%BD%8D%E7%9A%84%E5%AF%AB%E6%B3%95-wf-3-wf-4-%E5%85%A8%E9%AB%94%E9%81%A9%E7%94%A8) 下？

**Comment by trashmai** [comment]
常見物種順序只要更新 project 下的 speciesList array 值的順序就好。
[API 文件 WF 3](https://github.com/TaiBIF/camera-trap-api/wiki/API-Documentation#%E8%A8%88%E7%95%AB%E7%AE%A1%E7%90%86-wf-3)

**Comment by oahehc** [comment]
1. 滑入提示是寫死 for `空拍` `測試` `人` 三個類別嗎？
![image](https://user-images.githubusercontent.com/13633490/50053571-77d72a00-0172-11e9-8754-03ecb873cede.png)

2. 新增物種的欄位是下拉選單還是 free key in?
![image](https://user-images.githubusercontent.com/13633490/50053581-a94ff580-0172-11e9-8fc7-f9022b780b69.png)
