### ISSUE TITLE
API project deployment workflow

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#23]
- [x] 確認目前的 API 是否在 eb 上
- [x] workflow only on github
- [x] make sure github has the latest version
- [x] current method of API deployment
- [x] deploy ac2cb3fe00dc86ded2543f3e2126707cff912055 to eb 

Current manual deployment:
- [x] ZIP the following items
```
  .ebextensions
  client
  common
  server
  package.json
```
- [x] Upload at https://ap-northeast-1.console.aws.amazon.com/elasticbeanstalk/home?region=ap-northeast-1#/environment/dashboard?applicationName=camera%20trap%20api&environmentId=e-9sm333dgzr

- [x] Continuous Integration, using master branch for dev environment.

**Comment by cjk-halodule** [comment]
Current manual deployment:
1. ZIP the following items
```
  .ebextensions
  client
  common
  server
  package.json
```
2. Upload at https://ap-northeast-1.console.aws.amazon.com/elasticbeanstalk/home?region=ap-northeast-1#/environment/dashboard?applicationName=camera%20trap%20api&environmentId=e-9sm333dgzr

**Comment by rwu823** [comment]
我實測發現好像不需要 ZIP `client`？

**Comment by rwu823** [comment]
@cjk-halodule 請確認我 aws 權限是否正確？

我遇到如下錯誤：
```sh
ERROR: The current user does not have the correct permissions. Reason: Operation Denied. The security token included in the request is invalid.
```

**Comment by trashmai** [comment]
> @trashmai
> 
> 我實測發現好像不需要 ZIP `client`？

client directory 裡面放有 1. 透過 OrcID 登入 AWS Cognito 的前端靜態範例程式，以及 2. 登入後由前端直接上傳 S3 的範例程式，兩者皆是供測試使用。目前在 https://(api.)camera-trap.tw/explorer/ 底下測試涉及權限檢查的 API 時，會需要用到登入程式取得的 cookie。上傳 S3 的範例程式在前端確認上傳機制跟做法後則不再需要。

**Comment by trashmai** [comment]
> @cjk-halodule 請確認我 aws 權限是否正確？
> 
> 我遇到如下錯誤：
> 
> ```shell
> ERROR: The current user does not have the correct permissions. Reason: Operation Denied. The security token included in the request is invalid.
> ```

@rwu823 請問你是遇到以下狀況嗎？
https://stackoverflow.com/questions/38460457/operation-denied-error-when-deploying-an-elastic-beanstalk-app-using-awsebcli
你的權限目前是全開的狀態，如果是執行 eb cli 的問題，可能要請你設定與檢查一下 aws-access-id 與 aws-secret-key，或是到 AWS 的 IAM 更新一下 security credentials 的內容然後再重新試試看。

**Comment by cjk-halodule** [comment]
再請 @rwu823 把這個流程 port 到目前的 API 環境喔。

**Comment by cjk-halodule** [comment]
no longer applicable.
