### ISSUE TITLE
7.4 有效照片與目擊事件，7.5 初測延遲

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#24]
Must have
- [x] 7.4 API 接口 接受前端查詢條件，執行計算
- [x] 7.5 API 接口 接受前端查詢條件，執行計算
- [x] 7.4 計算程式開發
- [x] 7.5 計算程式開發
- [x] 7.4 計算完成回傳結果
- [x] 7.5 計算完成回傳結果

Good to have
- [ ] 每次計算紀錄條件及 log
- [ ] log 包含時間
需要前端介面提供顯示 log 的地方

Related to TaiBIF/camera-trap-webapp#55

**Comment by trashmai** [comment]
相關 API 已完成。
