### ISSUE TITLE
https://api.camera-trap.tw

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#26]
- [x] 建立 DNS entry
- [x] 將 DNS 指向 api-dev (CameraTrapApi-env)
- [ ] ~nginx 設定加上 port 443 for api.camera-trap.tw~

**Comment by trashmai** [comment]
Nginx 不需要設定 443，https 由 AWS load balancer 與 Cloudfront 處理。

**Comment by rwu823** [comment]
@cjk-halodule 請問現在 DNS 在哪管理？我是不是需要有權限

**Comment by cjk-halodule** [comment]
AWS 的 DNS 是  Route53 - 我已經設定好囉

**Comment by cjk-halodule** [comment]
目前的設定：
Cloudfront http->https
EB load balance conf: disable port 80, 所以全部加密

**Comment by cjk-halodule** [comment]
由於這個 dev 環境目前不在 VPC 內，若未來也沒有打算放進去，我想應該要實作
[Terminating HTTPS on EC2 Instances Running Node.js](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/https-singleinstance-nodejs.html)
