### ISSUE TITLE
4.16 版本紀錄

### ISSUE THREAD

**Issue by trashmai** [TaiBIF/camera-trap-api#27]
版本紀錄需要依照前端採用的資料更新方式設計批次更新以外的機制。

@diabloevagto:
/annotation-revision/query
這隻 api 的 modifiedBy 請改成要顯示的使用者名稱

Related to TaiBIF/camera-trap-webapp#5

**Comment by kelp404** [comment]
編輯 Annotation 時自動新增版本紀錄

**Comment by kelp404** [comment]
@trashmai 
請問尚未自動新增版本紀錄的 API 如下嗎？
POST /media/annotation/{id}/multimediaTokens
PUT /media/annotation/{id}/multimediaTokens/{fk}

**Comment by kelp404** [comment]
<img width="641" alt="2018-11-30 11 05 22" src="https://user-images.githubusercontent.com/1680868/49266125-df615a00-f48f-11e8-9301-a69f81181871.png">
