### ISSUE TITLE
3.6 計畫成員

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#31]
- [x] Suggest endpoint /project/{$projectId}/user/add, instead of /project/add-user-to-project
- [x] Implement /project/{$projectId}/user/delete/{$userId}
- [ ] Main script to work on:
TaiBIF/camera-trap-api/blob/master/common/models/ctp-user.js

Post
```
{
  "userId": $userId, // OrcID_XXXX-XXXX-XXXX-XXXX
  "projectId": $projectId, // 欲加入的計畫id
  "role": $role // 角色，
}
```
Response
```
{
  "userId": $userId, // OrcID_XXXX-XXXX-XXXX-XXXX
  "projectId": $projectId, // 欲加入的計畫id
  "projectTitle": "", 加入計畫名稱 
  "name": "", // 姓名
  "email": "", // 電子郵件
  "role": $role // 角色，
}
```

- [x] Document to update:
https://github.com/TaiBIF/camera-trap-api/wiki/project-user

Related to TaiBIF/camera-trap-webapp#64

**Comment by rwu823** [comment]
@cjk-halodule 
-  Suggest endpoint /project/user/add, instead of /project/add-user-to-project
 這必要換嗎？我怕影響到前端？

**Comment by cjk-halodule** [comment]
description updated. to implement:
1. /project/{$projectId}/user/add
2. /project/{$projectId}/user/delete/{$userId}

**Comment by rwu823** [comment]
API 已完成:

## 新增 user 角色到專案
### POST /project/:projectId/user/add/:userId
```json
{ "roles": [] }
```

## 移除 user 出專案
### POST /project/:projectId/user/remove/:userId

**Comment by cjk-halodule** [comment]
Considered implemented in v1.
