### ISSUE TITLE
10 個人設定

### ISSUE THREAD

**Issue by trashmai** [TaiBIF/camera-trap-api#33]
#### 10.1.1 登出
- [x] 前端登出後，一併清理後端 API 用的 session 資料
#### 10.1.2 設定
- [x] 修改使用者名稱與電子郵件
post to /ctp-user/bulk-update
```
[{
  "_id": OrcID_XXXX-XXXX-XXXX-XXXX,
  "$set": {
    "name": "New Name",
    "email": "New Email"
  }
}]
```
- [x] 文件
#### 10.1.2 快速鍵設定
- [ ] Model 建立 (至少要 _id (md5 of user_id:projectTitle), userId, projectTitle, speciesHotKey: [{species, hotKey}, ...])
- [ ] 讀取、儲存用的 API (可先掛上 bulk-update with $upsert)

Related to TaiBIF/camera-trap-webapp#69

**Comment by cjk-halodule** [comment]
Proposed format to attached to user object:
```
"settings": {
  "setting": {
    "hotkeys": [
      {
        "speciesName": "",
        "hotkey": ""
      },
      {
        "speciesName": "",
        "hotkey": ""
      },
    ]
  },
}
```
考慮到每個使用者可能有不同計畫的編輯需要，因此清單應該不需要和個別計畫綁在一起。

**Comment by cjk-halodule** [comment]
@rwu823 請在 https://github.com/TaiBIF/camera-trap-api/issues/31 使用者新增時把 10.1.2 的快速鍵設定寫入 user 物件？

**Comment by rwu823** [comment]
aa0a653590b79159ec2af19dff06e0da3b534625 已完成

## API 用法

### GET /ctp-user/me

如果有設定過會多一組 `speciesKeys` 欄位(會關連此 user 在所有計畫中有辨識出的物種), null 即由前端決定預設鍵

```json
"speciesKeys" : {
      "空拍": "AR",
      "工作照": "WP",
      "定時測試": null,
      "鼬獾": null,
      "水鹿": null,
      "山羌": null
	}
```

更新與重置 hotkeys
### PATCH /ctp-user/me/update

全所有 keys 送進來：
```json
{
	"speciesKeys" : {
		"物種" : "KEY",
		"物種2" : "KEY2",
		"物種3" : "KEY3",
	}
}
```

重置-> 看到 null 即由前端決定預設鍵
```json
{
	"speciesKeys" : null
}
```

**Comment by oahehc** [comment]
這支 API success 的 response 有點怪, 建議回更新成功後的 user profile
![image](https://user-images.githubusercontent.com/13633490/50088753-e1246f00-023e-11e9-828d-c8138448b9ce.png)

![image](https://user-images.githubusercontent.com/13633490/50088764-e8e41380-023e-11e9-81f1-dd9f9c2d8d63.png)

**Comment by oahehc** [comment]
`PATCH /ctp-user/me/update`
type PATCH 似乎沒設定 CORS
![image](https://user-images.githubusercontent.com/13633490/50090248-ee435d00-0242-11e9-9d80-f875bd1ec746.png)

**Comment by cjk-halodule** [comment]
@trashmai ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cjk-halodule** [comment]
在 f3b4c9 中加入 PATCH - 再看看是否 okay 了？

**Comment by oahehc** [comment]
`PATCH /ctp-user/me/update`
response 200, 但 data 沒有更新, update 完再 get 還是舊的資料

**Comment by cjk-halodule** [comment]
Kelp 更新過後請 @oahehc 再試一次？我可以幫忙確認。

**Comment by oahehc** [comment]
還是一樣, submit success, 但 refresh 後 `/me` 中的 speciesKeys 還是舊資料沒有更新成功

`/ctp-user/me/update` response
![image](https://user-images.githubusercontent.com/13633490/50398734-e3457b00-07b4-11e9-8033-de0dfe49764c.png)

`/me` result
![image](https://user-images.githubusercontent.com/13633490/50398759-053efd80-07b5-11e9-9e84-59b245abc5f7.png)

**Comment by cjk-halodule** [comment]
Implemented in v1 as #96
