### ISSUE TITLE
時間數值的一致格式

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#35]
目前從 API 文件來看，日期格式有： 
```
"dailyTestTime": [ // 可先略過這項
          {
            "since": 1539593959,
            "time": "12:00:00"
          }
        ],
```
```
"projectStartDate": "2018-10-15 // 計畫時間：起",
"projectEndDate": "2018-12-10 // 計畫時間：迄",
```
```
"abnormalStartDate": "2017/02/08", // 異常資料時間 起
"abnormalEndDate": "2017/03/01", // 異常資料時間 迄
```
```
      "created": 1540788756.494,
      "modified": 1542014471.609,
```
```
      "corrected_date_time": "2017-02-09 17:28:29",
```

- [ ] 應決定一致的 API 時間儲存格式
- [ ] 應決定一致的前端時間顯示格式
- [ ] 時間格式應在 key 命名中指明，或在 API 文件中說明

**Comment by cjk-halodule** [comment]
@diabloevagto @oahehc 請給意見囉

**Comment by oahehc** [comment]
如果要統一但又要涵蓋上述樣式, 應該是用 timestamp

**Comment by cjk-halodule** [comment]
所以是不論前端 widget 顯示什麼，一律都用 timestamp 寫入？然後顯示時間時再從 timestamp 轉？

**Comment by oahehc** [comment]
我的想法是這樣
看有沒有人有其他意見

**Comment by trashmai** [comment]
目前很多不用 timestamp 的理由是保存原始輸入資訊以供複查(相機可能會設定錯誤、還有EXIF的時間格式可能有出入、時區轉換差異)，再來就是減少前端多一道 render 手續，這兩塊以外用的部分我同意用 timestamp。

dailyTestTime.time 是資料檢核用的，直接用 regex 就可以確認是否為定時測試照片。不然「每天中午12時」要以 timestamp 來表達並不方便。

**Comment by kelp404** [comment]
會把 timestamp 除以 1000 的原因是什麼呢？
https://github.com/TaiBIF/camera-trap-api/blob/master/common/mixins/timeStamp.js#L11-L21

因為浮點數存進資料庫後在拿出來有可能會不一樣。
https://stackoverflow.com/questions/44693985/floating-point-numbers-do-not-match-in-aggregation

**Comment by cjk-halodule** [comment]
@trashmai : 「因為 javascript 的時間是微秒。」Hope this helps?

**Comment by kelp404** [comment]
以我的經驗來說我習慣存 iso8601（2018-12-03T03:23:54.275Z），如果是跨國服務來說資料庫一定是 UTC，然後在前端用 JavaScript 轉成當地時間，因為有些國家有夏時令的問題，很難在後端處理。

MongoDB 好像可以用 ISODate https://docs.mongodb.com/manual/core/shell-types/
可以存到微秒

**Comment by cjk-halodule** [comment]
考慮 MongoDB 支援 ISODate，也許我們就以此格式儲存？
然後前端在準備 request JSON 時大概是用到這個 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString ?

**Comment by cjk-halodule** [comment]
no longer applicable
