### ISSUE TITLE
500 or 502 response

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#37]
@oahehc mentioned:

/project/related-to-me => 500
/announcement/query => 502
/ctp-user/me => 500
/announcement/notifications => 502

**Comment by trashmai** [comment]
這幾個是需要登入才能用的 API，在 localhost 測試時需要一些額外的 headers 設定。

可以看 TaiBIF/camera-trap-webapp 下的 `src/util/fetch.js` 這支程式。

另外也需要改裡面的 BASE_URL 為最新的 https://api-dev.camera-trap.tw/v0.8

**Comment by cjk-halodule** [comment]
@oahehc 有困難請再回報喔

**Comment by oahehc** [comment]
感謝回覆
Thomas 協助修正 BASE_URL 已正常,
另外 API un-auth, 缺參數等建議改回 4xx,
5xx 主要用在 server error
