### ISSUE TITLE
顯示單一計畫所有樣區和相機地點的 project/* endpoint

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#39]
如題，Related to TaiBIF/camera-trap-webapp#39

project/* 似乎沒有能夠調出一個計畫下所有樣區的說明？

**Comment by trashmai** [comment]
直接 GET https://api-dev.camera-trap.tw/project/測試計畫1
- cameraLocations 屬性就是一個計畫下所有的相機地點。
- site, subSite 都是 cameraLocations 的子屬性。
- site 的位置用 cameraLocations 的座標算幾何中心。

**Comment by cjk-halodule** [comment]
剛和 @trashmai 討論，在不更動目前 projectTitle 設計目的（用來關連同一個計畫下的所有資料）下：
- [ ] 我們使用 db 產生的 _id  作為 API project 的 key，所以應可以用 project/{id} 來調資料，用 project/?projectTitle=${projectTitle} 來找到 id.
- [ ] 前端 projectTitle 輸入後即不可更改，用來確保 md5 的穩定性

**Comment by cjk-halodule** [comment]
已改為 直接 GET https://api-dev.camera-trap.tw/project/${projectId}
請 @oahehc 確認是否足夠計算？

**Comment by oahehc** [comment]
原始期望是能直接提供該project的樣區/子樣區選單, 而非完整的project資料,
不過Thomas已有處理由project資料過濾出選單的功能,
所以這需求後續再補即可

**Comment by cjk-halodule** [comment]
Implemented in V1.
