### ISSUE TITLE
3.1 計畫管理 (計畫基本資訊)

### ISSUE THREAD

**Issue by oahehc** [TaiBIF/camera-trap-api#46]
應該會有一支 API for 計畫基本資訊編輯？
![image](https://user-images.githubusercontent.com/13633490/48977409-7f0b9a80-f0d4-11e8-900d-58a36ce0c347.png)

畫面可編輯的欄位如下
```
    "projectTitle": "測試計畫1 // 計畫名稱",
    "shortTitle": "測1 // 計畫簡稱",
    "funder": "林務局 // 委辦單位",
    "projectId": "FB-test-cameratrap-01 // 計畫編號",
    "principalInvestigator": "測試principalInvestigator // 計畫主持人",
    "projectStartDate": "2018-10-15 // 計畫時間：起",
    "projectEndDate": "2018-12-10 // 計畫時間：迄",
    "adminArea": [ // 計畫地區, 見 WF 2.3.7
      "苗栗縣",
      "新竹縣"
    ],
    "abstract": "// 計畫摘要",
    "remarks": "// 備註",
```

**Comment by trashmai** [comment]
@oahehc 
POST to `/project/bulk-update`
```
[{
    "_id": "測試計畫1", // filter condition
    "projectTitle": "測試計畫1", // for access control
    "$set": { // set values
      "projectTitle": 不允許更改
      "shortTitle": "測1 // 計畫簡稱",
      "funder": "林務局 // 委辦單位",
      "projectId": "FB-test-cameratrap-01 // 計畫編號",
      "principalInvestigator": "測試principalInvestigator // 計畫主持人",
      "projectStartDate": "2018-10-15 // 計畫時間：起",
      "projectEndDate": "2018-12-10 // 計畫時間：迄",
      "adminArea": [ // 計畫地區, 見 WF 2.3.7
        "苗栗縣",
        "新竹縣"
      ],
      "abstract": "// 計畫摘要",
      "remarks": "// 備註"
  }
}]
```

**Comment by oahehc** [comment]
@cjk-halodule 
"projectTitle": 不允許更改 => 這部分請協助確認一下前端是不show欄位還是disable input

@trashmai 
1. 若部分欄位未傳, 是會保留原資料還是被改成空白？
2. 其他 project 編輯功能(3.2,3.4...)會開新 api 還是一併整合在這支?
3. `"_id": "測試計畫1", // filter condition`
	=> _id 會改為由系統生成 unique key?
4. `"projectTitle": "測試計畫1", // for access control`
	=> 所以 project title 不允許重複, 否則權限抓取會有錯誤？

**Comment by cjk-halodule** [comment]
Thanks @oahehc please disable input.

**Comment by trashmai** [comment]
@oahehc 
1. 使用 `/bulk-update` 時， `$set` 只會改變有列出的部分，未傳的部分會保留db中的原有資料。
2. 目前都合併在這支。(其他 model 的基本資料編輯方式也相同)
3. 是
4. 是 (暫時如此，如果3要改，4未來亦可統一改成使用 _id )

**Comment by cjk-halodule** [comment]
@oahehc 目前 API 應已使用 _id, 請確認此票是否仍有需求？

**Comment by oahehc** [comment]
如果改用_id,
是否表示 projectTitle 應該調整回可以編輯？
或是就維持現在的版本？
