### ISSUE TITLE
[Suggestion] Misc

### ISSUE THREAD

**Issue by rwu823** [TaiBIF/camera-trap-api#5]
- [ ] Unified file naming (I think `_` is not generally convention in JS community.)
    e.g.
https://github.com/TaiBIF/camera-trap-api/blob/master/server/boot/create_indexes.js

- [ ] ESLint rules should extend Airbnb and integrate pre-commit hooks (also [prettier](https://prettier.io/)).
- [ ] Separate out ESLint rules for easy to share in each repo (maybe is called `TaiBIF/eslint-base` )
- [ ] CI/CD integration.
- [ ] Until / API testing.
- [ ] Remove sensitive information switch to .env instead of.
- [ ] Don't put builded code in repository.
- [ ] Add `node` in package.json
- [ ] use `yarn` instead of `npm` (optional but strongly recommend.)
- [ ] clean up unnecessary packages
  - [ ] `eslint-plugin-react`
  - [ ] `serve-favicon`
  - [ ] ...etc

**Comment by cjk-halodule** [comment]
1. agree. residue of PHP background.
2. and also Vue specific rules?
3. yes please
4. once knowing the status of the API project, tests can be developed
5. agree
6. should we .gitignore that, and clean up the history?

**Comment by cjk-halodule** [comment]
Considered addressed.
