### ISSUE TITLE
log management

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#57]
系統的 log 處理應該按照類別 (status, debug, error ...) 紀錄在可以設定的位置，避免直接輸出在 console 中。

需要一個訊息單元統一處理系統端(logging)及需要送到 response 的狀態。

**Comment by kelp404** [comment]
`config.isDebug` 關掉的話就不會印 console。
`config.enableLog` 打開的話就會紀到 MongoDB 中。
<img width="1355" alt="螢幕快照 2019-05-06 上午11 46 26" src="https://user-images.githubusercontent.com/1680868/57205963-cdfb1b80-6ff4-11e9-9ee1-05c632e1276e.png">

**Comment by cjk-halodule** [comment]
那麼我想現階段的部署 config.enableLog 都打開囉。謝謝。
