### ISSUE TITLE
登入機制重構

### ISSUE THREAD

**Issue by kelp404** [TaiBIF/camera-trap-api#65]
current authentication：
```js
try {
  // TODO: camera-trap-user-id 只在測試環境使用，正式環境要把這個 headers 拿掉
  userId = req.headers['camera-trap-user-id'] || req.session.user_info.userId;
} catch (e) {
  callback(new errors.Http403('使用者未登入'));
}
```
current login flow:
![set-cookie](https://user-images.githubusercontent.com/1680868/49362354-9290b400-f719-11e8-8b42-e600562221fe.png)

問題：
1. 跨域名 ajax response 的 set-cookie 是不會被寫進去的。
2. 正式上線後我們不應該用 headers['camera-trap-user-id'] 來認使用者，任何人只要知道使用者 id 後就能用他的身份登入。
3. 如果沒有 session 的話下載 csv 相關的功能都失效。 https://github.com/TaiBIF/camera-trap-api/issues/29

**Comment by cjk-halodule** [comment]
剛有新 user 登入但沒發現新的帳號資訊寫進後端資料庫，可請再確認一次？
