### ISSUE TITLE
project cameraLocations 缺少架設日期

### ISSUE THREAD

**Issue by oahehc** [TaiBIF/camera-trap-api#66]
API response 缺少架設日期資訊
relate to: https://github.com/TaiBIF/camera-trap-webapp/issues/62
![image](https://user-images.githubusercontent.com/13633490/49444877-65243300-f80b-11e8-8caf-ba7f239ca522.png)

**Comment by cjk-halodule** [comment]
Not even in the data model 👎

**Comment by cjk-halodule** [comment]
前端可先略過架設日期欄位？

**Comment by oahehc** [comment]
yes, 已先隱藏架設日期欄位

**Comment by trashmai** [comment]
ac69b1d12f564dd3f74738e4117ab15a8c100ee1
