### ISSUE TITLE
用來檢查計畫名稱是否重覆的 endpoint

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#67]
需要在送出表單前提示使用者計畫名稱是否已經已經有人使用。

建議 endpoint
/project/title-duplication-check
POST
```
{
  "projectTitle": "$currentTitleValue"
}
```
response
```
{
  "duplicateExists": true // or false
}
```
Related to TaiBIF/camera-trap-webapp#102

**Comment by trashmai** [comment]
已照上述提議實作。
