### ISSUE TITLE
4.10 編輯模式 (操作相關_滑鼠右鍵) 複製一列並貼上/刪除列

### ISSUE THREAD

**Issue by trashmai** [TaiBIF/camera-trap-api#68]
- [x] `POST /media/annotation/:id/token/:index/replicate`
直接複製 _id === :id 的第 :index 個 token，插入到 annotation.tokens 的最後一個元素
- [x] 插入下一行的操作實際上要調整 tokens 的順序
i. e. 假設有 tokens 0, 1, 2，複製第 0 個的結果會插入到 1 的位置，剩下的 token 在 array 中向後順移，index 變為 2,3。新的 tokens array 是 0, 1 (new, replicated from 0), 2(原本的1), 3(原本的2)
- [x] `POST /media/annotation/:id/token/:index/delete`
直接刪除 _id === :id 的第 :index 個 token。當 tokens.length == 1 時不會再刪除。
- [x] 刪除後調整 tokens 的順序
i. e. 假設有 tokens 0, 1, 2，刪除第 1 個的結果，原 token index > 1 的元素在 array 中向前順移。新的 tokens array 是 0, 1 (原本的2)
- [ ] 權限管理

**Comment by cjk-halodule** [comment]
可否說明建議實作細節？

**Comment by trashmai** [comment]
method 改為 post 以免誤觸

**Comment by cjk-halodule** [comment]
no longer applicable.
