### ISSUE TITLE
Fix all ESLint rules

### ISSUE THREAD

**Issue by rwu823** [TaiBIF/camera-trap-api#7]
Once #6 PR is merged. we'll get many errors. like this, 😅

![image](https://user-images.githubusercontent.com/890063/48307944-0ca6a080-e593-11e8-8e3d-2a5134e77759.png)

So anyone can help to fix it?

cc @cjk-halodule

**Comment by cjk-halodule** [comment]
我對 unexpected function expression 有點怕怕的。我想等 #8 完全後再來跑比較保險？

**Comment by rwu823** [comment]
That's OK

**Comment by cjk-halodule** [comment]
Under this project, I've done
```
$git pull
$npm install -g eslint
$eslint --fix
```
But it shows ```$eslint --help```
Did I miss anything?

**Comment by rwu823** [comment]
it is done.
