### ISSUE TITLE
新增欄位清單應只顯示 fieldStatus === approved

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#70]
GET /data-field-available 取得欄位時, 應該只會給 fieldStatus === approved 的資料

**Comment by cjk-halodule** [comment]
是 ```/data-field-available``` 喔

**Comment by rwu823** [comment]
API 已完成:

### GET /data-field-available/approved

**Comment by cjk-halodule** [comment]
no longer applicable.
