### ISSUE TITLE
CameraAbnormalStatus 要能 query 整個 project 不限年份

### ISSUE THREAD

**Issue by oahehc** [TaiBIF/camera-trap-api#75]
relate https://github.com/TaiBIF/camera-trap-webapp/issues/15#issuecomment-449542906

**Comment by kelp404** [comment]
請問是這隻 API 嗎？
https://github.com/TaiBIF/camera-trap-api/wiki/location-month-abnormal#%E5%8F%96%E5%BE%97%E7%9B%B8%E6%A9%9F%E7%95%B0%E5%B8%B8%E5%80%BC

**Comment by kelp404** [comment]
如果是為了實作「WF 4.17 a 側邊目錄＿錯誤提示」請使用這隻 API
https://github.com/TaiBIF/camera-trap-api/wiki/annotation#%E4%B8%80%E6%AC%A1%E5%8F%96%E5%BE%97%E6%89%80%E6%9C%89%E6%A8%A3%E5%8D%80%E6%98%AF%E5%90%A6%E6%9C%89%E9%8C%AF%E8%AA%A4
ref: https://github.com/TaiBIF/camera-trap-api/issues/43

如果不是的話請告訴我要修改的 endpoint。

**Comment by oahehc** [comment]
yes, thanks
