### ISSUE TITLE
檔案上傳失敗時全部退掉

### ISSUE THREAD

**Issue by kelp404** [TaiBIF/camera-trap-api#81]
+ 如果上傳一個 zip 中有多張圖片，其中一張的 exif 沒有時間資訊時不應該新增任何 annotation。
+ 如果上傳一個 csv 中有多筆資料，其中一筆有問題（沒有時間、樣區...等）時不應該新增任何 annotation。

**Comment by kelp404** [comment]
已實作先驗證全部資料後再全部儲存。
驗證 exif：
https://github.com/TaiBIF/camera-trap-api/blob/32901bb28bb0b1104e9d61029633be4baf8e6d62/src/tasks/media-worker.js#L246-L255

驗證 csv 每筆資料的必填欄位：
https://github.com/TaiBIF/camera-trap-api/blob/32901bb28bb0b1104e9d61029633be4baf8e6d62/src/common/utils.js#L510-L517

**Comment by cjk-halodule** [comment]
Makes sense. Proceed to frontend.
