### ISSUE TITLE
上傳檔案後如果有重複的話顯示通知讓使用者決定是否覆蓋

### ISSUE THREAD

**Issue by kelp404** [TaiBIF/camera-trap-api#82]
如果上傳 .csv 中有資料重複時，annotation 應標註，並且設定 upload session 為等待使用者確定、發送通知給使用者要求後續動作。
等使用者確認覆蓋後才將 annotation 解除標註，使用者取消覆蓋的話退掉全部的 annotation。

**Comment by kelp404** [comment]
POST /api/v1/me/upload-session/:uploadSessionId/_overwrite
81f607e7aef15f42d21088744809628ed14f874e

POST /api/v1/me/upload-sessions/:uploadSessionId/_cancel
a9cbee69fdd9783682ad110656085f310e3eb015

**Comment by cjk-halodule** [comment]
Makes sense. Documentation checked. Proceed to frontend.

**Comment by cjk-halodule** [comment]
@kelp404  這裡可以再確認註記上傳資料重覆檢查的條件嗎？
我記得是：
1. CSV: 同一相機位置同一時間已有資料
2. 影像檔: 同一相機位置同一時間已有原始檔案檔名相同的資料

**Comment by kelp404** [comment]
檢查重複的查詢是這樣：
https://github.com/TaiBIF/camera-trap-api/blob/68e5cb5c4d49f5b22b01e77515ffb22010dfc73a/src/tasks/media-worker.js#L423-L429
<img width="1180" alt="螢幕快照 2019-05-11 下午6 08 23" src="https://user-images.githubusercontent.com/1680868/57568288-c9c96680-7417-11e9-9cd5-b3f381c4f18b.png">
跟流程圖是一樣的，條件中沒有樣區是因為相機位置就可以推出是哪一個樣區，所以不需要查樣區。

檔名不在檢查是否重複的範圍內，只要重複時是會覆蓋的，這個在 wireframe 上沒有，是我問你的。
https://github.com/TaiBIF/camera-trap-api/commit/5ce4f37fbf191ef431d9911601cbb68fb79080d6

**Comment by cjk-halodule** [comment]
謝謝。這樣 WF 要更新來反映現況。
