### ISSUE TITLE
新增 API 提供加入計畫成員前檢查帳號是否存在

### ISSUE THREAD

**Issue by kelp404** [TaiBIF/camera-trap-api#83]
新增 `GET /api/v1/users` 使用 `email`, `orcId` 搜尋使用者。

請參考：
https://github.com/TaiBIF/camera-trap-api/wiki/API-v1-Document#get-projectsprojectidcamera-locations
這是提供新增相機位置前檢查是否有同名的相機位置。
程式碼位置：
https://github.com/TaiBIF/camera-trap-api/blob/c3d710a8af2cda56f2266479048da84435f05c7d/src/handlers/camera-location-handler.js#L14-L57

**Comment by cjk-halodule** [comment]
所以新增帳號時是先用這支 API, 然後 projects/{pId}/members 才有帳號可以加嗎？

**Comment by kelp404** [comment]
對

**Comment by cjk-halodule** [comment]
http://52.192.70.91/api/v1/users?user=Chihjen%20Ko
```
{
    "index": 0,
    "size": 100,
    "total": 0,
    "items": []
}
```

http://52.192.70.91/api/v1/users?name=Chihjen%20Ko
```
{
    "message": "user: This field is required."
}
```

和[文件](https://cameratraptw.docs.apiary.io/#/reference/users/search-users/search-users/200?mc=reference%2Fusers%2Fsearch-users%2Fsearch-users%2F200) 不一致。

希望可以明確地使用 /users{?name,email,orcid}來查詢。

**Comment by kelp404** [comment]
我寫錯了，是 `user`。
https://github.com/TaiBIF/camera-trap-api/commit/35fd11f6f3c0c36a379622f82b63d9670bc36110#diff-2625016b50d68d922257f74801cac29c

**Comment by cjk-halodule** [comment]
Verified.
