### ISSUE TITLE
聯絡我們功能實作

### ISSUE THREAD

**Issue by kelp404** [TaiBIF/camera-trap-api#90]
需要實作一個 `POST /api/v1/issues` 的 API。

IssueModel 已經開了。
https://github.com/TaiBIF/camera-trap-api/blob/master/src/models/data/issue-model.js

有一個功能是讓使用者上傳附件，FileType 是 `issue-attachment`。
https://github.com/TaiBIF/camera-trap-api/blob/master/src/models/const/file-type.js#L7

<img width="1081" alt="螢幕快照 2019-04-23 下午3 57 30" src="https://user-images.githubusercontent.com/1680868/56564427-8cc04000-65e0-11e9-8ed2-c1d18e0a0d85.png">

Related to: https://github.com/TaiBIF/camera-trap-vueapp/issues/74

**Comment by cjk-halodule** [comment]
```
@moogoo78 : “12.3 聯絡我們”  如果寄信給系統管理員, 是不是也要寄一封給提問題的人, 例如: 我們已經收到您的問題/意見 …. 之類的
```
可以喔。

**Comment by moogoo78** [comment]
目前進度 commit, 功能還差附檔 (AttachmentFile) 上傳
https://github.com/TaiBIF/camera-trap-api/commit/f2da6d7af4264d3bb38b9f1fc89fd620f631383b

考慮的問題:
- FileModel 要加 issueAttachment 的 switch case 判斷? 要不要上傳 S3 ?
- 如果上傳 S3, 要像其他檔案一樣, 從 api/v1/files 上傳檔案?
- 如果不上傳 S3 直接在 mail 加 Attachment 也要考慮處理方式:
    - 直接用SES javascript SDK
      https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendRawEmail-property
   - 比較方便也許用 noadmailer module 處理
      https://medium.com/@xoor/sending-emails-with-attachments-with-aws-lambda-and-node-js-e6a78500227c

**Comment by kelp404** [comment]
我會改成不發信給提出問題的人，因為規格上沒有。
發信給管理員會保留但這也是不在規格上的。

**Comment by cjk-halodule** [comment]
Related to: #147 

請注意 12.3 中的意見類型我們還要找到對應的方式

**Comment by kelp404** [comment]
email 通知應寄給資料庫中所有的系統管理者帳號。
<img width="622" alt="螢幕快照 2019-05-07 下午1 57 09" src="https://user-images.githubusercontent.com/1680868/57275133-14717880-70d0-11e9-8bd2-ee81598e525c.png">
