### ISSUE TITLE
[GET] /system-announcements

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#94]
Notifications [GET /system-announcements]
https://cameratraptw.docs.apiary.io/#/reference/system/announcements

**Comment by kelp404** [comment]
notification type:
https://github.com/TaiBIF/camera-trap-api/blob/a2df8ece1426f178ea798259e466939255824933/src/models/const/notification-type.js#L2

需要實作 API 取得分頁的系統公告，使用 expiredTime 判定要撈哪些資料出來。
https://github.com/TaiBIF/camera-trap-api/blob/a2df8ece1426f178ea798259e466939255824933/src/models/data/notification-model.js#L46-L52

**Comment by cjk-halodule** [comment]
@moogoo78 來試試補文件？

**Comment by cjk-halodule** [comment]
https://cameratraptw.docs.apiary.io/#/reference/system/announcements/retrieve-notification/200?mc=reference%2Fsystem%2Fannouncements%2Fretrieve-notification%2F200
