### ISSUE TITLE
[GET] /me

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#95]
Retrieve profile [GET /me]
https://cameratraptw.docs.apiary.io/#/reference/account/profile

**Comment by kelp404** [comment]
快速鍵未設計
<img width="1108" alt="螢幕快照 2019-04-24 下午6 07 54" src="https://user-images.githubusercontent.com/1680868/56651603-01b47800-66bc-11e9-9068-47aae511481f.png">

**Comment by kelp404** [comment]
[doc] Added a field `hotkeys` at the API GET, PUT /me.
22132cae24cafebebd2995ca6faf5bdbd7514242

**Comment by cjk-halodule** [comment]
Verified.
