### ISSUE TITLE
[PUT] /me

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#96]
Update profile [PUT /me]
https://cameratraptw.docs.apiary.io/#/reference/account/profile/update-profile/200?mc=reference%2Faccount%2Fprofile%2Fupdate-profile%2F200

**Comment by kelp404** [comment]
快速鍵未設計
<img width="1108" alt="螢幕快照 2019-04-24 下午6 07 54" src="https://user-images.githubusercontent.com/1680868/56651584-f4978900-66bb-11e9-9be2-3fa85bd2412c.png">

**Comment by kelp404** [comment]
22132cae24cafebebd2995ca6faf5bdbd7514242

**Comment by cjk-halodule** [comment]
Proceed to front end https://github.com/TaiBIF/camera-trap-vueapp/issues/71
